### ISSUE TITLE
Copy goes wrong with AzCopy 10.5.0 (works with 10.4.3)

### ISSUE THREAD

**Issue by rneeft** [Azure/azure-storage-azcopy#1106]
##### Note: The version is visible when running AzCopy without any argument
azcopy version 10.5.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

azcopy.exe cp "PowerToys" "https://#############we.blob.core.windows.net/$web?sv=2018-03-28&si=################&sr=c&sig=######################################%%3D

### What problem was encountered?
```
INFO: Scanning...

failed to perform copy command due to error: no SAS token or OAuth token is present and the resource is not public
```
### How can we reproduce the problem in the simplest way?

- Create storage account
- Set as static website
- Create SAS token
- Upload files with the specified command

### Have you found a mitigation/solution?

Yes, using version 10.4.3

### Background
We have our click once applications uploaded to a Azure blob storage (static website). We are using the AzCopy tool to upload the click once artifacts to Blob storage:

```yaml
- download: current
  displayName: Download PowerToys Artifacts
  artifact: PowerToys

- task: PowerShell@2
  displayName: 'Download AzCopy Tool'
  inputs:
    workingDirectory: '$(Pipeline.Workspace)'
    targetType: 'inline'
    script: |
      If(!(Test-Path 'azcopy.exe')){
      Invoke-WebRequest -Uri "https://aka.ms/downloadazcopy-v10-windows" -OutFile AzCopy.zip -UseBasicParsing
      Expand-Archive ./AzCopy.zip ./AzCopy -Force
      Get-ChildItem ./AzCopy/*/azcopy.exe | Move-Item -Destination $env:Pipeline_Workspace}

- task: CmdLine@2
  displayName: 'Update PowerToys to blob storage'
  inputs:
    script: 'azcopy.exe cp "PowerToys" "https://#############we.blob.core.windows.net/$web?sv=2018-03-28&si=################&sr=c&sig=######################################%%3D" --recursive=true'
    workingDirectory: '$(Pipeline.Workspace)'
```
_Due to different (prive) Azure Account we are not able to use build in AzCopy task in Azure DevOps_

This was working fine until some time ago, build are now failing. 

using the workaround (to download an older version) everything is working as expected.

```yaml
- task: PowerShell@2
  displayName: 'Download AzCopy Tool'
  inputs:
    workingDirectory: '$(Pipeline.Workspace)'
    targetType: 'inline'
    script: |
      If(!(Test-Path 'azcopy.exe')){
      Invoke-WebRequest -Uri "https://azcopyvnext.azureedge.net/release20190128/azcopy_windows_amd64_10.0.7.zip" -OutFile AzCopy.zip -UseBasicParsing
      Expand-Archive ./AzCopy.zip ./AzCopy -Force
      Get-ChildItem ./AzCopy/*/azcopy.exe | Move-Item -Destination $env:Pipeline_Workspace}
```
