### ISSUE TITLE
Azure DevOps - Azcopy task inside Template

### ISSUE THREAD

**Issue by DAL3001** [Azure/azure-storage-azcopy#1168]
### Which version of the AzCopy was used? 

I'm not explicitly calling AzCopy, just via the Azure DevOps task version 4 defined as: 

`- task: AzureFileCopy@4`

### What command did you run?

File copy task is defined inside a YAML file called template_webcontent.yml that is used as a job template in another YAML Pipeline. Here is the parameter and task definition inside  template_webcontent.yml: 

```yaml
parameters:
  artifactName: ''
  artifactDownloadPath: ''
  azureSubscription: ''
  storageAccount: ''
  webContainter: ''
  blobPrefixApp: ''
  blobPrefixStatic: ''

        - task: AzureFileCopy@4
          displayName: "Copy App files"
          inputs:
            SourcePath: "${{ parameters.artifactDownloadPath }}/*"
            azureSubscription: ${{ parameters.azureSubscription }}
            Destination: 'AzureBlob'
            storage: ${{ parameters.storageAccount }}
            ContainerName: ${{ parameters.webContainter }}
            BlobPrefix: ${{ parameters.blobPrefixApp }}
            AdditionalArgumentsForBlobCopy: '--exclude-pattern=static'

```

It is then referenced in the primary pipeline as: 

```yaml
- stage: "blobdeploydev"
  dependsOn: build
  displayName: "Deployment: Dev"
  
  pool:
    vmImage: 'windows-2019'
  
  jobs:
  - template: template_webcontent.yml@templates
    parameters:
      artifactName: 'site_content'
      artifactDownloadPath: '$(System.ArtifactsDirectory)/site_content'
      azureSubscription: 'something-nonproduction'
      storageAccount: 'storageaccount001'
      webContainer: '$web'
      blobPrefixApp: 'people'
```

In this case, "something-nonproduction" is a service connection in Azure Devops.

### What problem was encountered?

When the task runs from inside the template, it seems the login stage is skipped. Here is some output with the Sub ID removed. You'll see it imports the modules and then immediately disconnects without performing any of the login/copy steps. It throws a 409 too - which from the API documentation doesn't seem to be correct either?  

```
Starting: Copy App files
==============================================================================
Task         : Azure file copy
Description  : Copy files to Azure Blob Storage or virtual machines
Version      : 4.171.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy
==============================================================================
Import-Module -Name C:\Modules\az_3.1.0\Az.Accounts\1.9.3\Az.Accounts.psd1 -Global
Clear-AzContext -Scope Process
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
 Set-AzContext -SubscriptionId XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX -TenantId ***
Import-Module -Name C:\Modules\az_3.1.0\Az.Resources\1.8.0\Az.Resources.psd1 -Global
Import-Module -Name C:\Modules\az_3.1.0\Az.Storage\1.9.0\Az.Storage.psd1 -Global
Import-Module -Name C:\Modules\az_3.1.0\Az.Compute\3.1.0\Az.Compute.psd1 -Global
Import-Module -Name C:\Modules\az_3.1.0\Az.Network\2.1.0\Az.Network.psd1 -Global
Disconnect-AzAccount -Scope Process -ErrorAction Stop
Clear-AzContext -Scope Process -ErrorAction Stop
##[error]Public access is not permitted on this storage account. HTTP Status Code: 409 - HTTP Error Message: Public access is not permitted on this storage account.
ErrorCode: PublicAccessNotPermitted
ErrorMessage: Public access is not permitted on this storage account.
RequestId:ad8c3b26-001e-001a-1421-81b467000000
Time:2020-09-02T12:06:31.7446470Z
Finishing: Copy App files
```

### How can we reproduce the problem in the simplest way?

As above.

### Have you found a mitigation/solution?

Task works perfectly outside of a template. I assume this is something to do with how the parameters are expanded and runtime vs compile time? I have some other tasks (Terraform for example) that pass the service connection and user details as parameters in almost exactly the same way and these appear to work fine. 

Thanks
