### ISSUE TITLE
auto login failure using service principal

### ISSUE THREAD

**Issue by El-Gor-do** [Azure/azure-storage-azcopy#1755]
### Which version of the AzCopy was used? 
10.14.1

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
From a Windows command prompt, run the following commands
```
set AZCOPY_AUTO_LOGIN_TYPE=SPN
set AZCOPY_SPA_APPLICATION_ID=<clientId>
set AZCOPY_SPA_CERT_PATH=<path to my .pfx certificate>
set AZCOPY_TENANT_ID=<tenantId>
azcopy list https://<accountName>.blob.core.windows.net/<containerName>
```

### What problem was encountered?
AzCopy fails with `failed to obtain credential info: Login Credentials missing. No SAS token or OAuth token`

The certificate has a private key but no password. According to https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/storage/common/storage-use-azcopy-authorize-azure-active-directory.md#authorize-a-service-principal-by-using-a-certificate-1 the certificate **should** have a password, not **must** have a password.

The same tenant ID, client ID and certificate work fine when using C# and the Azure.Storage.Blobs package v12.8.0 to list blobs in a container.

### How can we reproduce the problem in the simplest way?
Run the commands mentioned above

### Have you found a mitigation/solution?
No

**Comment by siminsavani-msft** [comment]
Hi @El-Gor-do ! This is a known bug that we are currently looking into, please use [Autologin ](https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store))in the meantime.

**Comment by El-Gor-do** [comment]
I am already using autologin. I set the environment variable `AZCOPY_AUTO_LOGIN_TYPE` to `SPN`

**Comment by siminsavani-msft** [comment]
Thanks for updating me @El-Gor-do ! I have informed the team and we are taking a look at this issue. Thanks for your patience!

**Comment by adreed-msft** [comment]
Related to #1753

**Comment by El-Gor-do** [comment]
This bug is about authenticating with a certificate that does not have a password, not the same as #1805. It is still not fixed in AzCopy 10.16.0. Please reopen this bug.

**Comment by samcutcliffe** [comment]
Unsure if this is the best place for it, but im getting a similar issue running AzureFileCopy@6 in pipeline. The error is:
`Failed to perform Auto-login: PSContextCredential[31;1mGet-AzAccessToken: -REDACTED-;1mRun Connect-AzAccount to login`

The task block is as follows:

```yaml
      - task: AzureFileCopy@6
        inputs:
          SourcePath: "$(TF_CONFIG_FILE_PATH)"
          azureSubscription: '<serviceConnection>'
          Destination: 'AzureBlob'
          storage: '<storageaccount>'
          ContainerName: '<container>'
          BlobPrefix: "$(FOLDER)"
        name: AzureFileCopy
```

Apologies if this is the wrong place to post. I can provide greater context if appropriate

Thank you!
