### ISSUE TITLE
Auto login insecurity

### ISSUE THREAD

**Issue by Cybgak** [Azure/azure-storage-azcopy#2403]
### Which version of the AzCopy was used? 
10.21.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What command did you run?
azcopy login
### What problem was encountered?
It seems the "azcopy login" command is being deprecated which appears to leave no way to securely authenticate once and store the token for subsequent non-interactive use.
The suggested replacement; "auto login" requires either a secret or certificate password to be stored in plain text in environment variables in order for azcopy to be used non-interactively which feels like a retrograde step from a security point of view.
### How can we reproduce the problem in the simplest way?
n/a
### Have you found a mitigation/solution?
I can continue using "azcopy login" for now but for how long?
I could use auto login but then I have to store the service principal secret in an environment variable which seems insecure.
I suppose one could store the secret in a PowerShell file that runs the azcopy commands and use that to set the environment variable dynamically when you run the script but that's got to be even less secure even if I do lock down the files permissions.
What's the answer for non-interactive use cases?

**Comment by mattnorflus** [comment]
I ran into this scenario recently and found a section in the AzCopy documentation, [linked here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-service-principal?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=windows#authorize-by-using-azure-cli), which worked for me. My scenario is running in an ADO pipeline. We have a service connection linked to a Managed Identity in Azure. I used the AzureCLI task, using the service connection to login in the task, and then set the `$Env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"` variable. AzCopy used the token from the service connection to run the copy commands. The AzureCLI task handles the token security for you.

```
- task: AzureCLI@2
   displayName: Copy Sources & Submit SCA Request
   inputs:
    addSpnToEnvironment: true # optional, I used this to get the tenantId
    connectedServiceNameARM: <Service connection name>
    scriptType: ps
    scriptPath: 'path/to/script'
```

```
$Env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"
$Env:AZCOPY_TENANT_ID="$env:tenantId"
Write-Host "Launching $azCopyExePath to copy from $sourceLocation to $targetLocation"
& $azCopyExePath cp --recursive=true $sourceLocation $targetLocation
```
