### ISSUE TITLE
Cannot copy Cold tier Blob

### ISSUE THREAD

**Issue by SugaMi** [Azure/azure-storage-azcopy#2447]
### Which version of the AzCopy was used?
10.21.2
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy.exe copy "https://<StorageAccountA>.blob.core.windows.net/nfs/sample?sp=racwdymeop&st=2023-11-13T06:06:13Z&se=2023-11-13T14:06:13Z&spr=https&sv=2022-11-02&sr=b&sig=" "https://<StorageAccountB>.blob.core.windows.net/copytest?sp=racwdli&st=2023-11-13T06:06:51Z&se=2023-11-13T14:06:51Z&spr=https&sv=2022-11-02&sr=c&sig="

### What problem was encountered?
I cannot copy Cold tier blob to another Storage Account.

```
Accept: application/xml
   Content-Length: 0
   User-Agent: AzCopy/10.21.2 azsdk-go-azblob/v1.1.0 (go1.19.12; Windows_NT)
   X-Ms-Client-Request-Id: 8781ed33-667b-4aa3-47ae-aa9f436f8b5b
   x-ms-access-tier: 
   x-ms-blob-cache-control: 
   x-ms-blob-content-disposition: 
   x-ms-blob-content-encoding: 
   x-ms-blob-content-language: 
   x-ms-blob-content-md5: 
   x-ms-blob-content-type: 
   x-ms-blob-type: 
   x-ms-copy-source: 
   x-ms-version: 
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The value for one of the HTTP headers is not in the correct format.
   Content-Length: 326
   Content-Type: application/xml
   Date: Mon, 13 Nov 2023 06:07:24 GMT
   Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
   X-Ms-Client-Request-Id: 8781ed33-667b-4aa3-47ae-aa9f436f8b5b
   X-Ms-Error-Code: InvalidHeaderValue
   X-Ms-Request-Id: 91683045-e01e-003f-30f7-159b56000000
   X-Ms-Version: 2020-10-02
Response Details: ﻿<Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format. </Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>Cold</HeaderValue>
```

I think this Go SDK version doesn't support Cold tier.
v1.2.0 supports Cold tier.
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/CHANGELOG.md#120-2023-10-11

### How can we reproduce the problem in the simplest way?
Upload blob as Cold tier and copy this blob to another Storage

### Have you found a mitigation/solution?
AzCopy should update Go SDK.
